name: NerfKeepInventory
version: '1.0-SNAPSHOT'
main: mcplugins.nerfkeepinventory.NerfKeepInventory
api-version: 1.19
authors: [ dogloverblue ]
description: Nerfing keep inventory to only keep your hotbar, shulker boxes, and armour
